# 
---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to launch a Spot Fleet of Boin instances

Parameters:

  FleetSize:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 20
    Description: The target number of instances you want to use for folding
  
  SpotPrice:
    Type: Number
    Default: 0.5
    MinValue: 0.01
    MaxValue: 10
    Description: The maximum amount, in USD, you're willing to spend per instance, per hour (default $0.05)

  AmazonLinuxAmiID:
    Type: String
    Default: 'ami-047bb4163c506cd98'
    Description: Amazon Linux AMI ID obtained from https://aws.amazon.com/amazon-linux-ami/

  ProjectUrl:
    Type: String
    Default: 'https://boinc.bakerlab.org/rosetta/'
    Description: The url project that you want to contribute

  AccountKey:
    NoEcho: true
    Type: String
    Default: '2160444_c34a50dad95871dfd5043c2c0fbab546'
    Description: Your  weak or normal account key

Resources:

  SpotFleetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeImages
                  - ec2:DescribeSubnets
                  - ec2:RequestSpotInstances
                  - ec2:TerminateInstances
                  - ec2:DescribeInstanceStatus
                  - ec2:CreateTags
                Resource:
                  - '*'
              - Effect: Allow
                Action: iam:PassRole
                Condition:
                  StringEquals:
                    iam:PassedToService: ec2.amazonaws.com
                Resource:
                  - '*'

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
  
  EtherSpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt 'SpotFleetRole.Arn'
        SpotPrice: !Ref 'SpotPrice'
        AllocationStrategy: lowestPrice
        TargetCapacity: !Ref 'FleetSize'
        LaunchSpecifications:
          - InstanceType: m4.small
            ImageId: !Ref AmazonLinuxAmiID
            SecurityGroups:
              - GroupId: !GetAtt 'InstanceSecurityGroup.GroupId'
            UserData: !Base64
              Fn::Join:
                - ''
                - - "#!/bin/bash -xe\n"
                  - yum update -y
                  - yum install -y epel-release boinc-client boinc-manager
                  - yum install -y compat-libstdc++-296.i686 compat-libstdc++-33.i686 compat-libstdc++-33.x86_64 zlib.i686 libstdc++.i686
                  - cd /var/lib/boinc
                  - boinccmd --project_attach 
                  - !Ref 'ProjectUrl'
                  - ' '
                  - !Ref 'AccountKey'
